apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: grafana
  labels:
    io.kompose.service: grafana-pvc
  name: grafana-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
