apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  targetNamespace: grafana
  chart:
    spec:
      chart: grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
      version: 8.8.4
  interval: 1m0s
  values:
    replicaCount: 1
    plugins:
    - grafana-github-datasource
    volumes:
      - name: grafana-pvc
        persistentVolumeClaim:
          claimName: grafana-pvc