apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: default
  annotations:
    com.centurylinklabs.watchtower.enable: "false"
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discord-bot
  template:
    metadata:
      annotations:
        com.centurylinklabs.watchtower.enable: "false"
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: discord-bot
    spec:
      containers:
        - env:
            - name: OWNER
              value: '186538096580493312'
            - name: PREFIX
              value: '!!'
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: token-discord
                  key: token
          image: harshraj9812/hr-bot-jmusicbot:0.3.9
          name: discord-hr-music-bot
      restartPolicy: Always
