apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr-stack
  labels:
    io.kompose.service: plex-claim0
  name: plex-claim0
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30000Mi
