---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: raffle-nest-backend-ingress
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.raffle.local.wololoaeyoyo.com`)
      kind: Rule
      services:
        - name: raffle-nest-backend-service
          port: 80
    - match: Host(`raffle.local.wololoaeyoyo.com`)
      kind: Rule
      services:
        - name: raffle-nest-backend-service
          port: 80
  tls:
    secretName: local-wololoaeyoyo-com-tls
