apiVersion: v1
kind: Service
metadata:
  name: discord-bot
  namespace: default
  annotations:
    com.centurylinklabs.watchtower.enable: "false"
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: discord-bot
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: discord-bot
