apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web-ui
  labels:
    io.kompose.service: ollama
  name: ollama
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: ollama
    spec:
      containers:
        - env:
          - name: OLLAMA_MODEL
            value: "deepseek-r1:1.5b"
          - name: OLLAMA_NO_THINKING
            value: "true"
          - name: OLLAMA_SYSTEM_PROMPT
            value: "You are DeepSeek-R1, a reasoning model. Provide direct answers without detailed reasoning steps or tags."
          image: ollama/ollama:latest
          name: ollama
          ports:
            - containerPort: 27015
              protocol: TCP
          resources:
            requests:
              cpu: "2000m"
              memory: "2Gi"
            limits:
              cpu: "4000m"
              memory: "10Gi"
              nvidia.com/gpu: "0"
          volumeMounts:
            - mountPath: /root/.ollama
              name: ollama-claim0
      nodeSelector:
        deploygame: deepseek
      restartPolicy: Always
      volumes:
        - name: ollama-claim0
          persistentVolumeClaim:
            claimName: ollama-claim0



Deployment/web-ui/ollama dry-run failed (Invalid): Deployment.apps "ollama" is invalid: [spec.strategy.rollingUpdate:
 Forbidden: may not be specified when strategy `type` is 'Recreate', spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]
 string{"io.kompose.service":"ollama"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable]