apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: web-ui
spec:
  serviceName: "ollama"
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - env:
        - name: OLLAMA_MODEL
          value: deepseek-r1:1.5b
        - name: OLLAMA_KEEP_ALIVE
          value: "-1"
        - name: OLLAMA_NO_THINKING
          value: "true"
        - name: OLLAMA_SYSTEM_PROMPT
          value: "You are DeepSeek-R1, a reasoning model. Provide direct answers without detailed reasoning steps or tags."
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        resources:
          requests:
            cpu: "2000m"
            memory: "2Gi"
          limits:
            cpu: "4000m"
            memory: "10Gi"
            nvidia.com/gpu: "0"
        volumeMounts:
        - name: ollama-claim0
          mountPath: /root/.ollama
        tty: true
      volumes:
        - name: ollama-claim0
          persistentVolumeClaim:
            claimName: ollama-claim0