apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: web-ui
spec:
  serviceName: "ollama"
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        command: ["/bin/sh"]
        args: [ "-c", "ollama serve && sleep 2 && ollama pull deepseek-r1:1.5b && tail -f /dev/null" ]
        image: ollama/ollama:latest
        name: ollama
        ports:
        - containerPort: 11434
        resources:
          requests:
            cpu: "2000m"
            memory: "2Gi"
          limits:
            cpu: "4000m"
            memory: "10Gi"
            nvidia.com/gpu: "0"
        volumeMounts:
        - name: ollama-claim0
          mountPath: /root/.ollama
        tty: true
      nodeSelector:
        webui: deepseek
      volumes:
        - name: ollama-claim0
          persistentVolumeClaim:
            claimName: ollama-claim0