apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  namespace: web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-ui
  template:
    metadata:
      labels:
        name: web-ui
    spec:
      containers:
      - name: ghcr.io/open-webui/open-webui:main
        image: web-ui/web-ui:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      nodeSelector:
        webui: deepseek
      volumes:
        - name: web-ui-claim0
          persistentVolumeClaim:
            claimName: web-ui-claim0