apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  labels:
    io.kompose.service: mc-data
  name: mc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Mi
