apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: minecraft
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: minecraft
    spec:
      containers:
        - env:
            - name: BUNGEE_JAR_REVISION
              value: "1"
            - name: CFG_MOTD
              value: Powered by Docker
            - name: MAX_MEMORY
              value: 5G
            - name: MEMORY
              value: 5G
            - name: PLUGINS
              value: https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.2.1-SNAPSHOT%2B639/PAPER/ViaVersion-5.2.1-SNAPSHOT.jar,https://hangarcdn.papermc.io/plugins/ViaVersion/ViaBackwards/versions/5.2.0/PAPER/ViaBackwards-5.2.0.jar,https://download.geysermc.org/v2/projects/geyser/versions/2.5.1/builds/726/downloads/velocity
            - name: REPLACE_ENV_VARIABLES
              value: "true"
            - name: TYPE
              value: VELOCITY
          image: itzg/mc-minecraft
          name: minecraft
          ports:
            - containerPort: 25565
              protocol: TCP
            - containerPort: 19132
              protocol: UDP
          volumeMounts:
            - mountPath: /config/config.yml
              name: minecraft-claim0
            - mountPath: /server
              name: minecraft-data
      restartPolicy: Always
      volumes:
        - name: minecraft-claim0
          persistentVolumeClaim:
            claimName: minecraft-claim0
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data
