apiVersion: v1
kind: Service
metadata:
  namespace: default
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  ports:
    - name: "25565"
      port: 25565
      targetPort: 25577
    - name: "19132"
      port: 19132
      targetPort: 19132
  selector:
    io.kompose.service: proxy
