apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  labels:
    io.kompose.service: proxy-claim0
  name: proxy-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Mi
