apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-deployment
  namespace: cnpg-system
spec:
  chart:
    spec:
      chart: cnpg 
      sourceRef:
        kind: HelmRepository
        name: cnpg 
  interval: 1m0s
  values:    
    namespace: cnpg-system
    replicaCount: 1
    volumeMounts:
      - name: postgres-volume
        mountPath: /var/lib/postgresql/data
    env:
      - name: POSTGRES_USER
        value: "admin"
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: db_password
    volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-volume