apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-pvc
  namespace: cnpg-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
--- 