apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: radarr-claim0
  name: radarr-claim0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: radarr-claim1
  name: radarr-claim1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: radarr-claim2
  name: radarr-claim2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20000Mi
