apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: arr-stack
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:

      labels:
        io.kompose.service: prowlarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/Chicago
          image: lscr.io/linuxserver/prowlarr:latest
          name: prowlarr
          ports:
            - containerPort: 9696
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/localtime
              name: prowlarr-claim0
              readOnly: true
            - mountPath: /config
              name: prowlarr-claim1
      restartPolicy: Always
      volumes:
        - name: prowlarr-claim0
          persistentVolumeClaim:
            claimName: prowlarr-claim0
            readOnly: true
        - name: prowlarr-claim1
          persistentVolumeClaim:
            claimName: prowlarr-claim1
