apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr-stack
  labels:
    io.kompose.service: prowlarr-claim0
  name: prowlarr-claim0
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
