apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr-stack
  labels:
    io.kompose.service: prowlarr-claim0
  name: prowlarr-claim0
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr-stack
  labels:
    io.kompose.service: prowlarr-claim1
  name: prowlarr-claim1
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
