apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alloy
  namespace: alloy
spec:
  targetNamespace: alloy 
  chart:
    spec:
      chart: alloy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: grafana
      version: 1.1.2

  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: alloy-config
      valuesKey: values.yaml