apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-values
  namespace: alloy
data:
  values.yaml: |
    alloy:
      configMap:
        content: |-
          // Write your Alloy config here:
          logging {
            level = "debug"
            format = "logfmt"
          } 
          discovery.kubernetes "pods" {
            role = "pod"
          }
          loki.write "default" {
            endpoint {
              url = "http://loki-loki-gateway.loki.svc.cluster.local/loki/api/v1/push"
            }
          }
