apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fabric
  name: fabric
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fabric
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fabric
    spec:
      containers:
        - env:
            - name: EULA
              value: "TRUE"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: BUNGEE_JAR_REVISION
              value: "1"
            - name: CFG_MOTD
              value: Powered by Docker
            - name: MAX_MEMORY
              value: 8G
            - name: MEMORY
              value: 5G
            - name: REPLACE_ENV_VARIABLES
              value: "true"
            - name: TYPE
              value: AUTO_CURSEFORGE
            - name: VERSION
              value: 1.20.1
            - name: FORGE_VERSION
              value: 47.4.0
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cursegore-api-key
                  key: api-key
            - name: CF_SLUG
              value: better-mc-forge-bmc4 
            - name: CF_FILE_ID
              value: "6328403"
            - name: CF_EXCLUDE_MODS
              value: particle_effects             
          image: itzg/minecraft-server
          name: fabric
          ports:
            - containerPort: 25565
              protocol: TCP
            - containerPort: 19132
              protocol: UDP
          volumeMounts:
            - mountPath: /data
              name: fabric-data-vpc
      nodeSelector:
        server: fabric
      restartPolicy: Always
      volumes:
        - name: fabric-data-vpc
          persistentVolumeClaim:
            claimName: fabric-data-vpc

