apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  labels:
    io.kompose.service: zomboide-vpc
  name: zomboide-vpc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6G
