apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: projectzomboiddedicatedserver
  name: projectzomboiddedicatedserver
spec:
  ports:
    - name: "16261"
      port: 16261
      protocol: UDP
      targetPort: 16261
    - name: "16262"
      port: 16262
      protocol: UDP
      targetPort: 16262
    - name: "27015"
      port: 27015
      targetPort: 27015
  type: LoadBalancer
  selector:
    io.kompose.service: projectzomboiddedicatedserver
  
