apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: deluge-claim1
  name: deluge-claim1
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: deluge-claim0
  name: deluge-claim0
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
