apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonnar-route
  namespace: arr-stack
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure 
  routes:
    - kind: Rule
      match: Host(`sonarr.local.wololoaeyoyo.com`)
      services:
        - name: sonarr 
          port: 8989
  tls:
    secretName: local-wololoaeyoyo-com-tls
