apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  version: 8.16.0
  http:
    service:
      spec:
        type: ClusterIP
    tls:
      selfSignedCertificate:
        subjectAltNames:
          - dns: elasticsearch-es-http.elastic
  nodeSets:
  - name: elastic
    count: 3
    config:
      node.store.allow_mmap: false
