apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: elastic
  labels:
    io.kompose.service: elasticsearch-data
  name: elasticsearch-data
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
