apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: web-ui
  labels:
    io.kompose.service: ollama-claim0
  name: ollama-claim0
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
