apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sonnar-route
  namespace: arr-stack
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - web 
  routes:
    - kind: Rule
      match: Host(`local.wololoaeyoyo.com`)
      services:
        - name: sonarr 
          port: 80
          