apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: arr-stack
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: sonarr
    spec:
      containers:
        - env:
            - name: ARRPATH
              valueFrom:
                configMapKeyRef:
                  key: ARRPATH
                  name: config-sonarr
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  key: PGID
                  name: config-sonarr
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  key: PUID
                  name: config-sonarr
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: config-sonarr
          image: linuxserver/sonarr:latest
          name: sonarr
          ports:
            - containerPort: 8989
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: arr-claim2
            - mountPath: /data/downloads
              name: arr-claim0
            - mountPath: /data/downloads/tvshows
              name: arr-claim0
            - mountPath: /data/downloads/anime
              name: arr-claim0
      hostname: sonarr
      restartPolicy: Always
      volumes:
        - name: arr-claim0
          persistentVolumeClaim:
            claimName: arr-claim0
        - name: arr-claim2
          persistentVolumeClaim:
            claimName: arr-claim2

