apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  Namespace: arr-stack
  labels:
    io.kompose.service: sonarr-claim0
  name: sonarr-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  Namespace: arr-stack
  labels:
    io.kompose.service: sonarr-claim1
  name: sonarr-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  Namespace: arr-stack
  labels:
    io.kompose.service: sonarr-claim2
  name: sonarr-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  Namespace: arr-stack
  labels:
    io.kompose.service: sonarr-claim3
  name: sonarr-claim3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi