apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr-stack
  labels:
    io.kompose.service: sonarr-claim0
  name: sonarr-claim0
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr-stack
  labels:
    io.kompose.service: sonarr-claim1
  name: sonarr-claim1
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr-stack
  labels:
    io.kompose.service: sonarr-claim2
  name: sonarr-claim2
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arr-stack
  labels:
    io.kompose.service: sonarr-claim3
  name: sonarr-claim3
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi